version: '3.1'
services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGDATABASE}
    volumes:
      - posdb:/var/lib/postgresql/data
      - ./conf/initdb.d:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  posdb: