version: '3.1'
services:
  pos:
    build: .
    ports: ['5000:5000']
    depends_on: [db]
    command: -c settings.json

  db:
    image: postgres:10.3
    restart: unless-stopped
    expose: [5432]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - posdb:/var/lib/postgresql/data
      - ./conf/initdb.d:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports: ['8090:8080']

volumes:
  posdb:
